version: '3'

services:
  backend:
    container_name: Backend-Container
    build: ./Backend
    volumes:
      - './Backend:/usr/src/app'
    ports:
      - '8080:8080'
    environment:
      clientId: '${CLIENTID}'
      clientKey: '${CLIENTKEY}'
    restart: always
    networks:
      - backend
  frontend:
    container_name: Frontend-Container
    build: ./Frontend/Schrankeninspektor
    volumes:
      - './Frontend/Schrankeninspektor:/usr/src/app'
    ports:
      - '4200:80'
    restart: always
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
