# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Web-App Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        CLIENTID: ${{ secrets.CLIENT_ID }}
        CLIENTKEY: ${{ secrets.CLIENT_KEY }}
      run: |
        mvn clean install --file Backend/pom.xml
        mvn -B package --file Backend/pom.xml

  deploy:
    name: Deployment
    runs-on: self-hosted
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      - name: Start docker-compose
        run: |
          export CLIENTID=${{ secrets.CLIENT_ID }}
          export CLIENTKEY=${{ secrets.CLIENT_KEY }}
          docker compose down
          docker compose up --build -d
        if: github.event_name != 'pull_request'
